import { ArrowLeft, ShieldAlert } from "lucide-react";
import Link from "next/link";

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen bg-zinc-50 dark:bg-black text-zinc-900 dark:text-zinc-100 p-6 lg:p-8">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="inline-flex items-center gap-2 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    Back to Analyzer
                </Link>

                <div className="flex items-center gap-3 mb-6">
                    <ShieldAlert className="w-10 h-10 text-zinc-900 dark:text-white" />
                    <h1 className="text-4xl font-black tracking-tight">Disclaimer</h1>
                </div>

                <div className="bg-white dark:bg-zinc-900 rounded-2xl p-8 border border-zinc-200 dark:border-zinc-800 shadow-sm space-y-8">
                    <section>
                        <h2 className="text-xl font-bold mb-3">Not Medical Advice</h2>
                        <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed">
                            The content provided by this application, including the NOVA classification, nutritional analysis, and product suggestions, is for informational and educational purposes only. It is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or dietary changes.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3">Data Accuracy</h2>
                        <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed">
                            This application uses data from <a href="https://world.openfoodfacts.org/" target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:underline">OpenFoodFacts</a>, a collaborative, free, and open database of food products from around the world. While we strive to present accurate information:
                        </p>
                        <ul className="list-disc pl-5 mt-3 space-y-2 text-zinc-600 dark:text-zinc-400">
                            <li>Product data is user-contributed and may contain errors or inaccuracies.</li>
                            <li>Manufacturers may change product formulations, ingredients, or nutritional values at any time.</li>
                            <li>The NOVA classification is an automated estimate based on available data and may not always reflect the exact processing level of a product.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3">Algorithmic Analysis</h2>
                        <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed">
                            The "Why is this Ultra-Processed?" analysis and swap suggestions are generated by algorithms based on ingredient lists and product categories. These algorithms look for common markers of ultra-processing but may not capture every nuance or exception.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
